# Generated by Django 5.1.5 on 2025-01-27 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^(?=.*\\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[^\\w\\d\\s:])(\\S){8,16}$', ['password must contain 1 number (0 - 9)', 'password must contain min 1 uppercase letter', 'password must contain min 1 lowercase letter', 'password must contain min 1 alphanumeric character', 'password min 8 max 16 characters without spaces'])], verbose_name='password'),
        ),
    ]
