# Generated by Django 5.1.5 on 2025-02-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usermodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last logout'),
        ),
    ]
